import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { ThemeProvider } from "@mui/material";
import theme from "@/utils/theme";
import "./globals.scss";
import Navigation from "@/components/common/navigation";

const notoSansKr = Noto_Sans_KR({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "따뜻하게 품다 - 꼬꼬마켓",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={notoSansKr.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
